### ISSUE TITLE
NullPointerException on hovering over Litmus Paper

### ISSUE THREAD

**Issue by flaviocysne** [hjake123/reactive#16]
This issues is happening constantly in UniversIO modpack.
[crash-2023-07-24_07.30.52-client.txt](https://github.com/hjake123/reactive/files/12145399/crash-2023-07-24_07.30.52-client.txt)

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.StringTag.m_7916_()" because "reaction_status" is null
	at com.hyperlynx.reactive.items.LitmusPaperItem.buildMeasurmentText(LitmusPaperItem.java:46) ~[reactive-1.19.2-5d.jar%23443!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.hyperlynx.reactive.items.LitmusPaperItem.m_7373_(LitmusPaperItem.java:60) ~[reactive-1.19.2-5d.jar%23443!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23499!/:?] 
```

It doesn't happen always, but it surely happen while hovering items without Reactive tags, in a chest. Last time it happened, it was over a Lead (#minecraft:lead).

**Comment by hjake123** [comment]
This issue should only occur when hovering over Litmus Paper items from before the 5c update, and has been fixed as of 5e. Can you reproduce this without Litmus Paper being involved?

**Comment by hjake123** [comment]
(For reference, UniversIO currently uses the version 5d which, frustratingly, still has the crash

**Comment by hjake123** [comment]
If you have experienced it without Litmus Paper in your container open a new issue please
