### ISSUE TITLE
Apprentice's Salts Crash in 1.18.2-3c

### ISSUE THREAD

**Issue by hjake123** [hjake123/reactive#26]
Reproduced from CurseForge comment. Operative section:
```
java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "this.renderFunction" is null
	at com.hyperlynx.reactive.alchemy.rxn.AnnihilationReaction.render(AnnihilationReaction.java:24) ~[reactive-1.18.2-3c.jar%2356!/:?] {re:classloading}
	at com.hyperlynx.reactive.fx.CrucibleRenderer.renderReactions(CrucibleRenderer.java:55) ~[reactive-1.18.2-3c.jar%2356!/:?] {re:classloading}
	at com.hyperlynx.reactive.fx.CrucibleRenderer.render(CrucibleRenderer.java:85) ~[reactive-1.18.2-3c.jar%2356!/:?] {re:classloading}
	at com.hyperlynx.reactive.fx.CrucibleRenderer.m_6922_(CrucibleRenderer.java:28) ~[reactive-1.18.2-3c.jar%2356!/:?] {re:classloading}
```

**Comment by hjake123** [comment]
Fixed in upcoming release 1.18.2-3d
