### ISSUE TITLE
[Bug] When changed recipes , patchouli book return corrupted

### ISSUE THREAD

**Issue by DevDyna** [hjake123/reactive#30]
On changing some recipe all patchouli book was corrupted (i have try to fix without success)

Mod : reactive-1.19.2-7b
Patchouli : Patchouli-1.19.2-77
Forge : 43.3.7

![image](https://github.com/hjake123/reactive/assets/78147916/001768cd-c3d6-4563-95bc-e09d95b2a870)

[latest.log](https://github.com/hjake123/reactive/files/14451364/latest.log)

maybe caused by line 3405
<details>
<summary>[click to see]</summary>

```js
[15:22:00] [Render thread/ERROR]: Error compiling book reactive:journal, using empty contents
java.lang.RuntimeException: Error building entry reactive:intro/symbols
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:223) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$zne000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1181) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23477!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.7.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry reactive:intro/symbols page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:249) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	... 33 more
Caused by: java.lang.RuntimeException: Error setting up template processor
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:96) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:246) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	... 33 more
Caused by: java.lang.IllegalArgumentException
	at com.hyperlynx.reactive.integration.patchouli.TransmuteComponentProcessor.setup(TransmuteComponentProcessor.java:35) ~[reactive-1.19.2-7b.jar%23432!/:?]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:246) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23418!/:1.19.2-77]
	... 33 more```
</details>

**Comment by hjake123** [comment]
Ah it seems I throw an IllegalArgumentException if a recipe that a page is expecting is absent. I should probably just... not do that.

**Comment by hjake123** [comment]
Removing that check causes recipe pages to look like this if their recipe is removed 
![image](https://github.com/hjake123/reactive/assets/5803666/4322a48b-d9bf-47eb-9d49-a5a03743c4d9)

This looks kinda ugly imo but it's not a crash at least? I think Patchouli lets you make addon books somehow so maybe you can replace my entry with one that works in your pack

**Comment by hjake123** [comment]
To be released in 1.19.2-7c

**Comment by hjake123** [comment]
Actually, you didn't say you'd removed a recipe. If there's still an issue let me know

**Comment by DevDyna** [comment]
now it work , thank!
![image](https://github.com/hjake123/reactive/assets/78147916/22644bf2-a838-4323-bb96-6c189a36c67d)
